### ISSUE TITLE
Erroneous code in "Rust and Neovim - A Thorough Guide and Walkthrough"

### ISSUE THREAD

**Issue by Tokarak** [rsdlt/rsdlt.github.io#1]
I'll keep this concise, but I strongly encourage you to add a comment function on the website, or some way to directly contact you. It's unavoidable that you'll let errors like this through, otherwise.

I fell for this error; so have several other, but they didn't find the reason, as can be seen here neovim/neovim#20465. Again, it's important to catch errors because your audience is largely beginners.

The faulty code is here:
```
local rt = {
    server = {
        settings = {
            on_attach = function(_, bufnr)
                -- Hover actions
                vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
                -- Code action groups
                vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
                require 'illuminate'.on_attach(client)
            end,
            ["rust-analyzer"] = {
                checkOnSave = {
                    command = "clippy"
                }, 
            },
        }
    },
}
require('rust-tools').setup(rt)
```
As you can see, `rt` references itself. Also, `on_attach` goes in the server block according to official documentation. It appears you somehow derived this nonsense from an example in the official doc: 
```
local rt = require("rust-tools")
    
    rt.setup({
      server = {
        on_attach = function(_, bufnr)
          -- Hover actions
          vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
          -- Code action groups
          vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
        end,
      },
    })
```
`rt` here refers to rust-tools, which makes much more sense. 

I won't open a PR, since I'm not sure if this site is compiled html instead (and I don't want to investigate), but I'll adjust the code so you can paste it straight in. Here you go:
```
local rt = require("rust-tools")

rt.setup {
	server = {
		on_attach = function(_, bufnr)
			-- Hover actions
			vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
			-- Code action groups
			vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
		end,
		["rust-analyzer"] = {
			checkOnSave = {
				command = "clippy"
			},
		},
	},
}
```
Heads up, I use tabs, so run it through your formatter to keep your code consistent.

**Comment by Tokarak** [comment]
And, for anyone who may be here, here is my own personal config, using `rust-tool.nvim`'s codelldb integration through nvim-DAP :
```
local install_root_dir = vim.fn.stdpath "data" .. "/mason"
local extension_path = install_root_dir .. "/packages/codelldb/extension/"
local codelldb_path = extension_path .. "adapter/codelldb"
local liblldb_path = extension_path .. "lldb/lib/liblldb.dylib" -- not `.so`!

local rt = require("rust-tools")

rt.setup {
	server = {
		on_attach = function(_, bufnr)
			-- Hover actions
			vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
			-- Code action groups
			vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
		end,
		["rust-analyzer"] = {
			checkOnSave = {
				command = "clippy"
			},
		},
	},
	dap = {
		adapter = require('rust-tools.dap').get_codelldb_adapter(codelldb_path, liblldb_path)
	},
}
```

**Comment by rsdlt** [comment]
Hi @Tokarak, thanks for letting me know. Will update the guide.

Best.

Rodrigo

**Comment by Tokarak** [comment]
I may have been impolite in sections. I'm sorry; I'm just in a bit of a funny mood.

**Comment by rsdlt** [comment]
> I may have been impolite in sections. I'm sorry; I'm just in a bit of a funny mood.

No prob! Thanks for raising the issue. Best.

**Comment by rsdlt** [comment]
Guide has been updated with latest example code provided by the plugin page.
